{
 "title": "Twitter analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of tweets in the last minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  num as value\nFROM\n  total_tweet_count\n"
    }
   ]
  },
  {
   "title": "Number of tweets per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(window_start,'1m'),\n  num as value\nFROM\n  tweet_counts_per_minute\nWHERE $__timeFilter(window_start)"
    }
   ]
  },
  {
   "title": "Most used hashtags in last minute",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS time,\n  hashtag AS value,\n  num AS metric\nFROM hashtag_counts\nORDER BY metric DESC\n"
    }
   ]
  }
 ]
}